#!/bin/sh

#
# https://help.ubuntu.com/community/LiveCDCustomizationFromScratch
#
#

sudo apt-get --yes install xorriso syslinux
cp sources.list /tmp/


if [ -e work/chroot/home ]; then
  echo "work/chroot/home exists, assuming already debootstrap-ed"
  cd work
else
  sudo apt-get install debootstrap
  mkdir -p work/chroot
  cd work
  pwd
  sudo debootstrap --arch=amd64 trusty chroot
fi
  sudo cp /etc/hosts chroot/etc/hosts
  sudo cp /etc/resolv.conf chroot/etc/resolv.conf
  sudo cp /tmp/sources.list chroot/etc/apt/sources.list


export CHROOT_SCRIPT="chroot_script.tmp"

echo "#!/bin/sh"  | tee $CHROOT_SCRIPT

echo ""  | tee -a $CHROOT_SCRIPT
echo "mount none -t proc /proc"  | tee -a $CHROOT_SCRIPT
echo "mount none -t sysfs /sys"  | tee -a $CHROOT_SCRIPT
echo "mount none -t devpts /dev/pts"  | tee -a $CHROOT_SCRIPT
echo "export HOME=/root"  | tee -a $CHROOT_SCRIPT
echo "export LC_ALL=C"  | tee -a $CHROOT_SCRIPT
echo "apt-get update"  | tee -a $CHROOT_SCRIPT
echo "apt-get install --yes dbus"  | tee -a $CHROOT_SCRIPT
echo "dbus-uuidgen  | tee -a  /var/lib/dbus/machine-id"  | tee -a $CHROOT_SCRIPT
echo "dpkg-divert --local --rename --add /sbin/initctl"  | tee -a $CHROOT_SCRIPT
echo "ln -s /bin/true /sbin/initctl"  | tee -a $CHROOT_SCRIPT

if [ ! -e chroot/boot/vmlinuz* ]; then
  echo "apt-get --yes upgrade"  | tee -a $CHROOT_SCRIPT
  echo "apt-get install --yes ubuntu-standard casper lupin-casper"  | tee -a $CHROOT_SCRIPT
  echo "apt-get install --yes discover laptop-detect os-prober"  | tee -a $CHROOT_SCRIPT
  echo "apt-get install --yes linux-generic "  | tee -a $CHROOT_SCRIPT
fi
echo "apt-get install --yes kvm build-essential screen tmux vlan bridge-utils uml-utilities ndisc6 curl git network-manager"  | tee -a $CHROOT_SCRIPT
echo "apt-get install --yes openssh-server"  | tee -a $CHROOT_SCRIPT

echo ""  | tee -a $CHROOT_SCRIPT
echo ""  | tee -a $CHROOT_SCRIPT
echo "rm /var/lib/dbus/machine-id"  | tee -a $CHROOT_SCRIPT
echo "rm /sbin/initctl"  | tee -a $CHROOT_SCRIPT
echo "dpkg-divert --rename --remove /sbin/initctl"  | tee -a $CHROOT_SCRIPT
echo "apt-get clean"  | tee -a $CHROOT_SCRIPT
echo "rm /etc/resolv.conf"  | tee -a $CHROOT_SCRIPT
echo "rm -rf /tmp/*"  | tee -a $CHROOT_SCRIPT
echo ""  | tee -a $CHROOT_SCRIPT
echo "umount -lf /proc"  | tee -a $CHROOT_SCRIPT
echo "umount -lf /sys"  | tee -a $CHROOT_SCRIPT
echo "umount -lf /dev/pts"  | tee -a $CHROOT_SCRIPT
echo "echo chroot portion done"  | tee -a $CHROOT_SCRIPT
echo "rm -f /$CHROOT_SCRIPT" | tee -a $CHROOT_SCRIPT
echo "exit"  | tee -a $CHROOT_SCRIPT
echo ""  | tee -a $CHROOT_SCRIPT
echo ""  | tee -a $CHROOT_SCRIPT

sudo cp $CHROOT_SCRIPT chroot
sudo chmod +x chroot/$CHROOT_SCRIPT

sudo chroot chroot /$CHROOT_SCRIPT
rm $CHROOT_SCRIPT

if [ ! -e image/casper/vmlinuxz ]; then
  sudo apt-get install syslinux squashfs-tools genisoimage
  mkdir image image/casper image/isolinux image/install
  sudo cp chroot/boot/vmlinuz-*-generic image/casper/vmlinuz
  cp chroot/boot/initrd.img-*-generic image/casper/initrd.gz
  cp /usr/lib/syslinux/isolinux.bin image/isolinux/
  cp /boot/memtest86+.bin image/install/memtest
fi

cat >image/isolinux/isolinux.txt <<__EE__

************************************************************************

This is an Ubuntu Remix Live CD running from RAM.

Will boot target "livetoram" in a few seconds.

For the default live system, enter "live".  To run memtest86+, enter "memtest"

************************************************************************
__EE__

cat >image/isolinux/isolinux.cfg <<__EE__
DEFAULT livetoram
LABEL livetoram
  menu label ^Start Ubuntu Remix from RAM
  kernel /casper/vmlinuz
  append toram noprompt persistent file=/cdrom/preseed/ubuntu.seed boot=casper initrd=/casper/initrd.gz  --
LABEL live
  menu label ^Start or install Ubuntu Remix
  kernel /casper/vmlinuz
  append  file=/cdrom/preseed/ubuntu.seed boot=casper initrd=/casper/initrd.gz  --
LABEL check
  menu label ^Check CD for defects
  kernel /casper/vmlinuz
  append  boot=casper integrity-check initrd=/casper/initrd.gz  --
LABEL memtest
  menu label ^Memory test
  kernel /install/memtest
  append -
LABEL hd
  menu label ^Boot from first hard disk
  localboot 0x80
  append -
DISPLAY isolinux.txt
TIMEOUT 30
PROMPT 1 

#prompt flag_val
# 
# If flag_val is 0, display the "boot:" prompt 
# only if the Shift or Alt key is pressed,
# or Caps Lock or Scroll lock is set (this is the default).
# If  flag_val is 1, always display the "boot:" prompt.
#  http://linux.die.net/man/1/syslinux   syslinux manpage 
__EE__


sudo chroot chroot dpkg-query -W --showformat='${Package} ${Version}\n' | sudo tee image/casper/filesystem.manifest
sudo cp -v image/casper/filesystem.manifest image/casper/filesystem.manifest-desktop
REMOVE='ubiquity ubiquity-frontend-gtk ubiquity-frontend-kde casper lupin-casper live-initramfs user-setup discover1 xresprobe os-prober libdebian-installer4'
for i in $REMOVE 
do
        sudo sed -i "/${i}/d" image/casper/filesystem.manifest-desktop
done
sudo rm image/casper/filesystem.squashfs
sudo mksquashfs chroot image/casper/filesystem.squashfs 
printf $(sudo du -sx --block-size=1 chroot | cut -f1) > image/casper/filesystem.size

cat >image/README.diskdefines <<__EE__
#define DISKNAME Ubuntu 12.04 - amd64 **Remix**
#define TYPE binary
#define TYPEbinary 1
#define ARCH amd64
#define ARCHamd64 1
#define ARCHi386 0
#define DISKNUM 1
#define DISKNUM1 1
#define TOTALNUM 0
#define TOTALNUM0 1
__EE__


touch image/ubuntu

if [ ! -e image/.disk ] ; then
  mkdir image/.disk
  cd image/.disk
  touch base_installable
  echo "full_cd/single" > cd_type
  echo "Ubuntu Remix" > info
  echo "http://your-release-notes-url.com" > release_notes_url
  cd ../..
fi

sudo sh -c "(cd image && find . -type f -print0 | xargs -0 md5sum | grep -v "\./md5sum.txt" > md5sum.txt)"

cd image
# sudo mkisofs -r -V "UBUNTU1204" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o ../ubuntu-remix.iso .

# sudo genisoimage -r -V "UBUNTU1204" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o ../ubuntu-remix.iso .

# xorriso is better because you can just dd the .iso to the USB stick main device and it will boot

sudo xorriso -as mkisofs -r -J -joliet-long -l -cache-inodes -isohybrid-mbr /usr/lib/syslinux/isohdpfx.bin -partition_offset 16 -A "Ubuntu Live"  -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o ../ubuntu-xorriso.iso .

cd ..

